# Generated by Django 5.1.5 on 2025-01-15 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(help_text="Use - for southern latitudes."),
                ),
                (
                    "longitude",
                    models.FloatField(help_text="Use - for western longitudes."),
                ),
                ("elevation", models.IntegerField(help_text="Elevation in feet.")),
            ],
        ),
        migrations.CreateModel(
            name="MountainRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subranges",
                        to="core.mountainrange",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Peak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("prominence", models.IntegerField(help_text="In feet.")),
                ("isolation", models.FloatField(help_text="In miles.")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.location"
                    ),
                ),
                (
                    "mountain_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.mountainrange",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trailhead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.location"
                    ),
                ),
            ],
        ),
    ]
