# Generated by Django 5.1.5 on 2025-01-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_location_mountainrange_peak_trailhead"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peak",
            name="location",
        ),
        migrations.RemoveField(
            model_name="trailhead",
            name="location",
        ),
        migrations.AddField(
            model_name="peak",
            name="elevation",
            field=models.IntegerField(default=0, help_text="Elevation in feet."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="peak",
            name="latitude",
            field=models.FloatField(
                default=0, help_text="Use - for southern latitudes."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="peak",
            name="longitude",
            field=models.FloatField(
                default=0, help_text="Use - for western longitudes."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trailhead",
            name="elevation",
            field=models.IntegerField(default=0, help_text="Elevation in feet."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trailhead",
            name="latitude",
            field=models.FloatField(
                default=0, help_text="Use - for southern latitudes."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trailhead",
            name="longitude",
            field=models.FloatField(
                default=0, help_text="Use - for western longitudes."
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
