# Generated by Django 5.1.5 on 2025-01-15 22:07

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_peak_location_remove_trailhead_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColoradoSnowClimbsActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("guidebook_number", models.IntegerField(blank=True, null=True)),
                (
                    "distance",
                    models.FloatField(help_text="Round-trip distance in miles."),
                ),
                (
                    "gain",
                    models.IntegerField(help_text="Total elevation gain in feet."),
                ),
                (
                    "estimated_time_enroute",
                    models.IntegerField(blank=True, help_text="In minutes.", null=True),
                ),
                (
                    "yds_class",
                    models.FloatField(
                        blank=True,
                        help_text="Enter the highest grade in the case of multiple. Use .5 for +. e.g. 2/3+ -> 3.5.",
                        null=True,
                    ),
                ),
                (
                    "season_bitmap",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        validators=[core.models.validate_binary_string],
                    ),
                ),
                ("season_text", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "snow_steepness",
                    models.CharField(
                        choices=[
                            ("EA", "Easy (0-30 degrees)"),
                            ("MO", "Moderate (30-45 degrees)"),
                            ("ST", "Steep (45-60 degrees)"),
                            ("VS", "Very Steep (60-80 degrees)"),
                            ("VE", "Vertical (80-90 degrees)"),
                        ],
                        help_text="Enter the steepest listed.",
                        max_length=2,
                    ),
                ),
                (
                    "associated_peaks",
                    models.ManyToManyField(
                        blank=True, related_name="activities", to="core.peak"
                    ),
                ),
                (
                    "guidebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="core.guidebook",
                    ),
                ),
                (
                    "trailhead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Activities",
                        to="core.trailhead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colorado Snow Climbs Activity",
                "verbose_name_plural": "Colorado Snow Climbs Activities",
            },
        ),
    ]
