# Generated by Django 5.1.5 on 2025-01-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_coloradosnowclimbsactivity_associated_peaks_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bestsummithikesactivity",
            options={
                "verbose_name": "Best Summit Hikes Activity",
                "verbose_name_plural": "Best Summit Hikes Activities",
            },
        ),
    ]
