# Generated by Django 5.1.5 on 2025-01-15 23:10

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_bestsummithikesactivity_crowd_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="HikingColoradoActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("guidebook_number", models.IntegerField(blank=True, null=True)),
                (
                    "distance",
                    models.FloatField(help_text="Round-trip distance in miles."),
                ),
                (
                    "gain",
                    models.IntegerField(help_text="Total elevation gain in feet."),
                ),
                (
                    "estimated_time_enroute",
                    models.IntegerField(blank=True, help_text="In minutes.", null=True),
                ),
                (
                    "yds_class",
                    models.FloatField(
                        blank=True,
                        help_text="Enter the highest grade in the case of multiple. Use .5 for +. e.g. 2/3+ -> 3.5.",
                        null=True,
                    ),
                ),
                (
                    "season_bitmap",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        validators=[core.models.validate_binary_string],
                    ),
                ),
                (
                    "season_text",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EA", "Easy"),
                            ("MO", "Moderate"),
                            ("DI", "Difficult"),
                            ("MD", "Most Difficult"),
                            ("ST", "Strenuous"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "associated_peaks",
                    models.ManyToManyField(
                        blank=True, related_name="%(class)s_activities", to="core.peak"
                    ),
                ),
                (
                    "guidebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_activities",
                        to="core.guidebook",
                    ),
                ),
                (
                    "trailhead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_activities",
                        to="core.trailhead",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
