# Generated by Django 5.1.5 on 2025-01-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_hikingcoloradoactivity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hikingcoloradoactivity",
            options={
                "verbose_name": "Hiking Colorado Activity",
                "verbose_name_plural": "Hiking Colorado Activities",
            },
        ),
    ]
